Localsdk
eclipse-uprotocol/uprotocol-sdk-cpp pull request #11
Opened 2023-09-26 15:55 UTC by jvnaiduwin

2023-09-30 15:42 UTC, giorgiozoppi reviewed
Can we keep vcpkg support?

2023-10-05 17:56 UTC, MelamudMichael commented
> Can we keep vcpkg support?

Hi @giorgiozoppi 

For now we are going to support only redhat and yocto - so no need to vcpkg

2023-10-05 17:57 UTC, MelamudMichael approved these changes

2023-10-05 18:10 UTC, jvnaiduwin commented
> Can we keep vcpkg support?

As we have discussion with Michael, and he discussed with Steven we agreed upon 

"[Tuesday 1:29 PM] Michael Melamud

J Vignesh Naidu (C)  no need for vcpkg, we are supporting redhat and yocto at the moment 

[Tuesday 1:29 PM] Michael Melamud

this was the agreement with steven"

2023-10-10 22:01 UTC, linsonittoop approved these changes

2023-10-19 20:02 UTC, stevenhartley requested changes
I pulled the project and built per the README and it fails to find RapidJSON even thought I installed it with vcpkg.  Can you please check what is wrong?  The build is complaining of a missing RapidJSONConfig.cmake or rapidjson-config.cmake file

2023-10-19 20:06 UTC, stevenhartley requested changes
additional comments

2023-10-19 20:06 UTC, stevenhartley commented on uprotocol/tools/tools.h
Would this not be provided by some other external library?

2023-10-19 20:06 UTC, stevenhartley commented on uprotocol/proto/CMakeLists.txt
We should not include the cloudevent proto here, it should be pulled as an external dependency for the cloudevent builders.

2023-10-27 01:19 UTC, stevenhartley approved these changes
Change is now good and we can merge to the 1.5 branch

2023-10-27 01:19 UTC, merged